print ("retorno da funcao com sintaxe corrigida")
  print (n)
  print ("forma 1 de implementar o last")
  print (funcLast1 array)
  print ("forma 2 de implementar o last")
  print (funcLast2 array)
  print ("forma 1 de implementar o init")
  print (funcInit1 array)
  print ("forma 2 de implementar o init")
  print (funcInit2 array)
  print ("usando o last")
  print (b array)
  print ("usando o init")
  print (a array)